name: "Build Page"
description: "Build an index.html from the README.md"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: build.sh
      shell: bash
